# Generated by Django 4.0.4 on 2022-06-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='address',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='dni',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
