# Generated by Django 4.0.4 on 2022-06-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=200, null=True)),
                ('title2', models.CharField(blank=True, max_length=200, null=True)),
                ('text_footer', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(default='', upload_to='logo')),
            ],
        ),
    ]
